name: Public package on demond

on:
  workflow_dispatch:
    inputs:
      package_name:
        required: true

jobs:
  build_and_publish_package:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build package ${{ github.event.inputs.package_name }}
        run: |
          ./scripts/build_package.sh ${{ github.event.inputs.package_name }} ./app-output
  
      - name: Upload package ${{ github.event.inputs.package_name }}
        run: |
          ./scripts/upload_package.sh "${{ secrets.AZURE_STORAGE_BLOB_CONNECTION_STRING }}" ./app-output
