name: Public package on demond

on:
  workflow_dispatch:
    inputs:
      package_name:
        required: true

jobs:
  build_and_publish_package:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and upload package ${{ github.event.inputs.package_name }}
        run: |
          PACKAGES="${{ github.event.inputs.package_name }}"
          if [ "$PACKAGES" = "*" ]; then PACKAGES=`ls packages/`; fi
          for f in $PACKAGES; do
              echo build package: $f
              ./scripts/build_package.sh $f ./app-output

              echo upload package: $f
              ./scripts/upload_package.sh "${{ secrets.AZURE_STORAGE_BLOB_CONNECTION_STRING }}" ./app-output
              rm -rf ./app-output
          done